### ISSUE TITLE
Invalid v4l2loopback parameter

### ISSUE THREAD

**Issue by thallerod** [prabhakar-sivanesan/MS-Teams-background-changer#7]
https://github.com/prabhakar-sivanesan/MS-Teams-background-changer/blob/54ac333902e5dfedef0a131dc500f33e19668ddf/README.md?plain=1#L30 should read:
`sudo modprobe v4l2loopback video_nr=20 card_label="Virtual Camera 1"`

**Comment by prabhakar-sivanesan** [comment]
Hi,

Thanks for pointing out. I will verify and change that.
